# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180318_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 16, 51, 55, 753573, tzinfo=utc)),
        ),
    ]
